[tox]
envlist = django{42,52},quality
requires = tox-uv>=1

[pycodestyle]
exclude = .git,.tox
max-line-length = 120

[testenv]
runner = uv-venv-lock-runner
passenv =
    CODEJAIL_TEST_USER
    CODEJAIL_TEST_VENV
dependency_groups =
    django42: django42
    django52: test
allowlist_externals =
    make
    mkdir
commands =
    mkdir -p reports
    make clean
    make test_no_proxy
    make clean
    make test_proxy

[testenv:quality]
runner = uv-venv-lock-runner
dependency_groups = quality
allowlist_externals =
    make
commands =
    make quality
