name: Publish package to PyPi

on:
  release:
    types: [published]

jobs:

  push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - name: setup python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: 3.12

      - name: Install pip
        run: pip install pip

      - name: Install Dependencies
        run: pip install setuptools wheel

      - name: Build package
        run: python setup.py sdist bdist_wheel

      - name: Publish to PyPi
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_UPLOAD_TOKEN }}
